version: "3.8"
services:
  db:
    image: postgres:15.1
    volumes:
    - ./example_backup.sql:/example_backup.sql
    - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh
    ports:
      - 5432:5432
    # environment:
    #   POSTGRES_USER: 'postgres'
    #   POSTGRES_PASSWORD: 'admin'
    #   POSTGRES_DB: 'example_db'
      #POSTGRES_HOST: db
      #POSTGRES_PORT: 5432
    env_file:
      - ./.env
    restart: on-failure
  bot:
    build: .
    command: sh -c "python -m bot"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db